// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCybvqhPxSGBUF3jADLTlGrM39l38dfe8U',
    appId: '1:676595526174:web:3203c2d4f8ffa55c041c0f',
    messagingSenderId: '676595526174',
    projectId: 'flutter-chat-app-ln',
    authDomain: 'flutter-chat-app-ln.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ln.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxQi4R5OUY3bDE6cWTtZu7kNMAMFK4_hg',
    appId: '1:676595526174:android:095d75246355dae9041c0f',
    messagingSenderId: '676595526174',
    projectId: 'flutter-chat-app-ln',
    storageBucket: 'flutter-chat-app-ln.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxzg7pSMVoBiETTQK_jXYGxfNNoUpekbw',
    appId: '1:676595526174:ios:b01d6da4e6a605ce041c0f',
    messagingSenderId: '676595526174',
    projectId: 'flutter-chat-app-ln',
    storageBucket: 'flutter-chat-app-ln.appspot.com',
    iosClientId: '676595526174-8certf97b0e7kkf2pnlu7scfntvqi7dr.apps.googleusercontent.com',
    iosBundleId: 'com.lourenco.chatAppLn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxzg7pSMVoBiETTQK_jXYGxfNNoUpekbw',
    appId: '1:676595526174:ios:b01d6da4e6a605ce041c0f',
    messagingSenderId: '676595526174',
    projectId: 'flutter-chat-app-ln',
    storageBucket: 'flutter-chat-app-ln.appspot.com',
    iosClientId: '676595526174-8certf97b0e7kkf2pnlu7scfntvqi7dr.apps.googleusercontent.com',
    iosBundleId: 'com.lourenco.chatAppLn',
  );
}
